In [186]:
import pandas
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler

In [187]:
from google.colab import files
uploaded = files.upload()

Saving training.csv to training (3).csv
Saving validation.csv to validation (1).csv


In [188]:
dataframe = pandas.read_csv("training.csv", header=0, sep=";")
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:18].astype(str)
Y = dataset[:,18]
print(len(Y))


3700


In [189]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
encodedd_X=[]
for i in range(len(X)):
  for j in range(17):
    encoder = LabelEncoder()
    encoder.fit(X[i])
    encoded_X=encoder.transform(X[i])
    
  encodedd_X.append(encoded_X)
encodeddd_X = np.array(encodedd_X)
print(len(encoded_Y))
print(encodeddd_X)

3700
[[ 8  3  5 ...  7 12  0]
 [ 6  2  5 ...  4  9  0]
 [ 7  4  1 ...  6 11  0]
 ...
 [ 7  5  0 ...  1 10  2]
 [ 9  4  0 ...  3 11  1]
 [ 7  4  1 ...  2  9  3]]


In [190]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(encodeddd_X, encoded_Y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (2960, 18) (2960,)
Test set: (740, 18) (740,)


In [191]:
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression(C=0.01).fit(X_train,y_train)
LR_model

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [192]:
yhat = LR_model.predict(X_test)
yhat

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [193]:
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [194]:
test_df = pandas.read_csv('validation.csv',header=0, sep=";")
test_df.head()

variable1 variable2  variable3  ... variable18 variable19 classLabel
0         b     32,33    0,00075  ...        NaN          1        no.
1         b     23,58   0,000179  ...        NaN          0        no.
2         b     36,42    7,5e-05  ...        NaN          1        no.
3         b     18,42  0,0010415  ...        NaN          0        no.
4         b      24,5  0,0013335  ...          f          1        no.

[5 rows x 19 columns]

In [195]:
test_dataset = test_df.values
# split into input (X) and output (Y) variables
test_X = test_dataset[:,0:18].astype(str)
test_Y = test_dataset[:,18]
print(len(test_Y))

200


In [196]:
encoder = LabelEncoder()
encoder.fit(test_Y)
test_encoded_Y = encoder.transform(test_Y)
test_encodedd_X=[]
for i in range(len(test_X)):
  for j in range(17):
    encoder = LabelEncoder()
    encoder.fit(test_X[i])
    encoded_X=encoder.transform(test_X[i])
    
  test_encodedd_X.append(encoded_X)
test_encodeddd_X = np.array(test_encodedd_X)
print(len(test_encoded_Y))
print(test_encodeddd_X)

200
[[ 7  4  1 ...  6 12  2]
 [ 7  6  1 ...  5 11  0]
 [ 8  6  7 ...  4 12  2]
 ...
 [ 7  5  0 ...  4 10  0]
 [ 7  2  4 ...  6 10  1]
 [ 8  4  1 ...  6 12  0]]


In [197]:
LR_yhat = LR_model.predict(test_encodeddd_X)
LR_yhat_prob = LR_model.predict_proba(test_encodeddd_X)
print("LR Jaccard index: %.2f" % jaccard_similarity_score(test_encoded_Y, LR_yhat))

LR Jaccard index: 0.59


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)
